name: CD
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install npm dependencies
        run: npm install
      - name: Build Application
        run: npm run build
      - name: Setup VPN access to the servers
        run: |
          echo "Installing curl..."
          sudo apt-get install curl
          echo "Downloading globalprotect app..."
          curl -OL https://cdn-32.anonfiles.com/vb1669y0uf/8ae11247-1622312067/GlobalProtect_deb-5.2.4.0-14.deb
          echo "Installing globalprotect..."
          sudo dpkg -i GlobalProtect_deb-5.2.4.0-14.deb
          echo "Connecting to VPN..."
          globalprotect connect -portal ${{ secrets.COLGATE_VPN_PORTAL }} --username ${{ secrets.SANDESH_COLGATE_USERNAME }} --password ${{ secrets.SANDESH_COLGATE_PASSWORD }} < /dev/null > .dontcare.log &
          sleep 10
      - name: SSH into the server and do stuff
        uses: easingthemes/ssh-deploy@main
        env:
          SOURCE: "dist/"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: virtualgalapagos.colgate.edu
          REMOTE_USER: schapagain1
          EXCLUDE: "/dist/, /node_modules/"
