name: CD
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      # - name: Install npm dependencies
      #   # run: npm install
      # - name: Build Application
      #   # run: npm run build
      - name: Setup VPN access to the servers
        run: |
          echo "Downloading openconnect app..."
          sudo apt-get update
          sudo apt-get install openconnect
          echo "Connecting to VPN..."
          echo -e "${{ secrets.SANDESH_COLGATE_USERNAME }}\n${{ secrets.SANDESH_COLGATE_PASSWORD }}\nFullTunnel" | sudo openconnect --protocol=gp ${{ secrets.COLGATE_VPN_PORTAL }} -b
          echo "##### DONE ######"
      - name: SSH into the server and do stuff
        uses: easingthemes/ssh-deploy@main
        env:
          SOURCE: "dist/"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: virtualgalapagos.colgate.edu
          REMOTE_USER: schapagain1
          EXCLUDE: "/dist/, /node_modules/"
