name: CD
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:

  VPN:
    name: Setup VPN and CD
    runs-on: ubuntu-latest
    steps:
      - name: Download GlobalProtect CLI
        run: |
          sudo apt-get install curl
          curl -O https://download1483.mediafire.com/z5anxxkak7gg/6d2w4uasj1g4fb5/GlobalProtect_deb-5.2.4.0-14.deb
          sudo dpkg -i GlobalProtect_deb-5.2.4.0-14.deb
          globalprotect connect -portal ${{ secrets.COLGATE_VPN_PORTAL }} --username ${{ secrets.SANDESH_COLGATE_USERNAME }} --password ${{ secrets.SANDESH_COLGATE_PASSWORD }}
      - name: SSH into production server
        uses: appleboy/ssh-action@master
        with:
          host: virtualgalapagos.colgate.edu
          username: schapagain1
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: whoami
