name: CD
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:

  VPN:
    name: Setup VPN and CD
    runs-on: ubuntu-latest
    steps:
      - name: Download GlobalProtect CLI
        run: |
          apt install curl
          curl -O https://itsforms.wsu.edu/VPN/20210106/PanGPLinux-5.2.4-c14.tgz
          tar -xvzf PanGPLinux-5.2.4-c14.tgz
          cd PanGPLinux-5.2.4-c14
          sudo dpkg -i GlobalProtect_deb-5.2.4.0-14.deb
          globalprotect connect -portal ${{ COLGATE_VPN_PORTAL }} --username ${{ SANDESH_COLGATE_USERNAME }} --password ${{ SANDESH_COLGATE_PASSWORD }}
      - name: SSH into production server
        uses: appleboy/ssh-action@master
        with:
          host: virtualgalapagos.colgate.edu
          username: schapagain1
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: whoami
